// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQUS3U5dMUbPq3Xu7LxFdA8o0J9F7ys24',
    appId: '1:818835358905:web:b1ee8248f1557f0cc08768',
    messagingSenderId: '818835358905',
    projectId: 'flutter-talk-734c5',
    authDomain: 'flutter-talk-734c5.firebaseapp.com',
    storageBucket: 'flutter-talk-734c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ-TTe3xjP0mC8S--xHq0fmU7abgRd-ao',
    appId: '1:818835358905:android:a334820c749bb71cc08768',
    messagingSenderId: '818835358905',
    projectId: 'flutter-talk-734c5',
    storageBucket: 'flutter-talk-734c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQRBRCrVUDS00tgP624ueFRRp4FcimObA',
    appId: '1:818835358905:ios:9cb4e65f75b809a4c08768',
    messagingSenderId: '818835358905',
    projectId: 'flutter-talk-734c5',
    storageBucket: 'flutter-talk-734c5.firebasestorage.app',
    iosBundleId: 'com.example.talk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQUS3U5dMUbPq3Xu7LxFdA8o0J9F7ys24',
    appId: '1:818835358905:web:8d65b2676279c175c08768',
    messagingSenderId: '818835358905',
    projectId: 'flutter-talk-734c5',
    authDomain: 'flutter-talk-734c5.firebaseapp.com',
    storageBucket: 'flutter-talk-734c5.firebasestorage.app',
  );
}
